services:
  bokulog_web:
    image: nginx:alpine
    container_name: bokulog_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bokulog_app

  bokulog_app:
    build: ./docker/php
    container_name: bokulog_app
    volumes:
      - ./src:/var/www/html
    depends_on:
      - bokulog_db

  bokulog_db:
    image: mysql:8.0
    container_name: bokulog_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: bokulog
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - bokulog_db_data:/var/lib/mysql

volumes:
  bokulog_db_data:




